# Generated by Django 4.2.7 on 2024-01-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=100)),
                ('gambar_produk', models.ImageField(blank=True, null=True, upload_to='produk/')),
                ('rating_produk', models.DecimalField(decimal_places=2, max_digits=3)),
                ('harga_produk', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
